### ISSUE TITLE
Support Claude 3 Tools Schema

### ISSUE THREAD

**Issue by MLawlz** [cadifyai/tool2schema#63]
Claude 3 [was updated today](https://docs.anthropic.com/claude/docs/tool-use) to support Tools in a nearly identical schema to that of GPT-4. It would be awesome to have the ability to specify a different decorator type like `@ClaudeEnabled` that would change the schema from having a `parameters` key to an `input_schema` key to be out-of-the-box compatible with Claude.

Happy to help put in a PR for this if that'd be helpful!

**Comment by MLawlz** [comment]
And for anyone looking for a workaround at the moment, I've been fixing the schema with a few lines of code as follows:
```
for schema in schemas:
    if 'parameters' in schema:
        schema['input_schema'] = schema.pop('parameters')
```

**Comment by siliconlad** [comment]
Sorry didn't see this until now. This would be awesome to have! Happy to review the PR for this @MLawlz. Otherwise, I can probably work on this sometime over the next week or so.

Adding an extra value to `SchemaType` seems to me the simplest solution, so that you can get Claude 3 compatible schemas by calling

```python
from . import tools  # module of tools
claud_schemas = FindGPTEnabledSchemas(tools, SchemaType.CLAUDE_API)
```

(SchemaType.API should probably be renamed to SchemaType.OPENAI_API)

I'm not currently aware of use cases where having different decorators `@GPTEnabled` and `@ClaudeEnabled` is important, but happy to consider it if there is!

**Comment by siliconlad** [comment]
Tbf the Anthropic version makes more sense, although I suppose OpenAI's version would allow for other tools other than "functions" although I'm not sure what that would be...
