### ISSUE TITLE
Parameter values of type int should also work with type float

### ISSUE THREAD

**Issue by siliconlad** [cadifyai/tool2schema#67]
When calling `LoadGPTEnabled`, I have a situation where I'm passing `2` into a parameter of type `float` and it errors out when validating the type.

**Comment by siliconlad** [comment]
Perhaps an extra flag like `coerce_type` or something.

**Comment by lorenzocelli** [comment]
The first fix that comes to mind is (in `type_schema.py:142`):
```python
class ValueTypeSchema(TypeSchema):
    # ...

    def validate(self, value) -> bool:
        try:
            self.type(value)
            return True # Return true if the value can be converted to the type
        except ValueError:
            return False
```
But this might be too permissive. For example, I think every value can be converted to boolean.

Otherwise we could have a special case for float and int:
```python
def validate(self, value) -> bool:
    return (self.type is float and type(value) is int) or self.type == type(value)
```
But this might not work in other cases, if there are any. It depends on Python rules for implicit conversion. Reading online I did not find any other cases of implicit cast, so the special check might not be that bad.

**Comment by siliconlad** [comment]
Allowing implicit conversion from int to float looks good to me.
